feat: packer, packer workflow

diff --git a/.github/workflows/mvn_compile.yml b/.github/workflows/mvn_compile.yml
--- a/.github/workflows/mvn_compile.yml
+++ b/.github/workflows/mvn_compile.yml
@@ -10,7 +10,7 @@ jobs:
     
     steps:
       - uses: actions/checkout@v3
-      
+
       - name: Setup JDK 17
         uses: actions/setup-java@v3
         with:
@@ -18,3 +18,29 @@ jobs:
           distribution: 'temurin'
       - name: Build application with Maven
         run: mvn clean install -Dmaven.test.skip=true
+
+      - name: Setup `packer`
+        uses: hashicorp/setup-packer@main
+        id: setup
+        with:
+          version: latest
+
+      - name: Run `packer init`
+        id: init
+        run: "packer init ./webapp.pkr.hcl"
+
+      - name: Run `packer validate`
+        id: validate
+        run: |
+          if ! packer validate ./webapp.pkr.hcl ; then
+            echo "Validation check failed"
+            exit 1
+          fi
+
+      - name: Run `packer fmt`
+        id: fmt
+        run: |
+          if ! packer fmt -check ./webapp.pkr.hcl ; then
+            echo "Formatting check failed"
+            exit 1
+          fi
